export const ERROR_INCORECT_MESSAGE_FORMAT = 'ERROR_INCORECT_MESSAGE_FORMAT';
export const ERROR_APP_INCORRECT_COMMAND = 'ERROR_APP_INCORRECT_COMMAND';

export const ERROR_WEB3_GET_BALANCE = 'ERROR_WEB3_GET_BALANCE';
export const ERROR_WEB3_CURRENCY_DOES_NOT_EXIST = 'ERROR_WEB3_CURRENCY_DOES_NOT_EXIST';
export const ERROR_WEB3_LOCATION_DOES_NOT_EXIST = 'ERROR_WEB3_LOCATION_DOES_NOT_EXIST';

export const ERROR_INAPPROPRIATE_REQUEST_MESSAGE_FORMAT = 'ERROR_INAPPROPRIATE_REQUEST_MESSAGE_FORMAT';
